### ISSUE TITLE
TS2451: Cannot redeclare block-scoped variable (4)

### ISSUE THREAD

**Issue by teppeis** [teppeis/closure-library.d.ts#16]
```
all.d.ts(135682,8): error TS2451: Cannot redeclare block-scoped variable 'TokenTypes'.
```

introduced by https://github.com/angular/clutz/commit/65e524ba2c1c341966eb3415682aa1ba21bc8c27, https://github.com/teppeis/closure-library.d.ts/commit/894ca681e71df821aa899d08e6a7cab60ec22e6b
