### ISSUE TITLE
TS2300: Duplicate identifier (26)

### ISSUE THREAD

**Issue by teppeis** [teppeis/closure-library.d.ts#15]
```
all.d.ts(97646,5): error TS2300: Duplicate identifier 'ABORT'.
```

introduced by https://github.com/angular/clutz/commit/65e524ba2c1c341966eb3415682aa1ba21bc8c27, https://github.com/teppeis/closure-library.d.ts/commit/894ca681e71df821aa899d08e6a7cab60ec22e6b

**Comment by teppeis** [comment]
processUnprovidedTypes

- walkInnerSymbols: enum{goog.net.WebChannel.FailureRecovery.State}, goog.net.WebChannel.FailureRecovery.State
- walkInnerSymbols: enum{goog.net.WebChannel.FailureRecovery.FailureCondition}, goog.net.WebChannel.FailureRecovery.FailureCondition

**Comment by teppeis** [comment]
fixed: `goog.module.ModuleLoader` in https://github.com/angular/clutz/pull/831
